#!/bin/bash
if [[ "$#" -gt "0" ]]
then
    echo 'vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv'
    while (( "$#" ))
    do
        python3 ./ldaprunner.py "$1"
        shift  # Shift all the parameters down by one.
        if [[ "$#" -gt "0" ]]
        then
            echo '    ................................'
        fi
    done
    echo '^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^'
fi